ci: enable PMD checks (#5273)
* ci: enable PMD checks

* ci: record PMD check findings and align instructions

* ci: fix `java.lang.NoSuchMethodError`

Jenkins complaiend about:
```
Error when executing always post condition:
java.lang.NoSuchMethodError: No such DSL method 'pmd' found among steps [..., pmdParser, ...]
```

* ci: pmdParser expects xml

according to https://javadoc.jenkins.io/plugin/violations/hudson/plugins/violations/types/pmd/PMDParser.html